setup_environment: &setup_environment
  docker:
    - image: boosterfuels/circle-build:v1.0-python
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
working_directory: ~/project

version: 2
jobs:
  deploy:
    <<: *setup_environment
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/project
      - run:
          name: Build and push production docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t boosterfuels/purr:production .
            docker push boosterfuels/purr:production
workflows:
  version: 2
  install_test_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: 
                - master 
                - test 