setup_environment: &setup_environment
  docker:
    - image: messa/circleci-python-with-mongodb:3.6
    - image: circleci/postgres:9.6.9-alpine
      environment:
        POSTGRES_USER: circleci
        POSTGRES_DB: purr_test
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
working_directory: ~/project

version: 2
jobs:
  test:
    <<: *setup_environment
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/project
      - run:
          name: Test
          command: |
            sudo pip install -r requirements.txt
            python -m unittest discover ./tests/extract
            python -m unittest discover ./tests/load
            python -m unittest discover ./tests/transform
  publish-github-release:
    <<: *setup_environment
    steps:
      - attach_workspace:
          at: ./project
      - run:
          name: Build
          command: |
            printf "Triggering builds"
            BUILD_INFO=$(curl -X POST -H -d \
                "{}" \
                "https://circleci.com/api/v1/project/$ORGANIZATION/$PROJECT/tree/$BRANCH?circle-token=$CIRCLE_TOKEN")
            BUILD_INFO=$(curl -X POST -H -d \
                "{}" \
                "https://circleci.com/api/v1/project/$ORGANIZATION/$PROJECT1/tree/$BRANCH?circle-token=$CIRCLE_TOKEN")
            BUILD_INFO=$(curl -X POST -H -d \
                "{}" \
                "https://circleci.com/api/v1/project/$ORGANIZATION/$PROJECT2/tree/$BRANCH?circle-token=$CIRCLE_TOKEN")

workflows:
  version: 2
  install_test_deploy:
    jobs:
      - test:
          filters:
            branches:
              only: 
                - master
                - test
      - publish-github-release:
          requires:
            - test
          filters:
            branches:
              only: master 