setup_environment: &setup_environment
  docker:
    - image: boosterfuels/circle-build:v1.0-python
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
working_directory: ~/project

version: 2
jobs:
  build:
    <<: *setup_environment
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/project
      - run:
          name: Build and push production docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t boosterfuels/purr:production .
            docker push boosterfuels/purr:production
      - run:
          name: Test
          #command: ./tests/
  deploy:
    <<: *setup_environment
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/project
      - run:
          name: Build and push production docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t boosterfuels/purr:production .
            docker push boosterfuels/purr:production
      - run:
          name: Deploy production docker image
          # command: |

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"

workflows:
  version: 2
  install_test_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master 
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master 
      - publish-github-release:
          requires:
            - deploy
          filters:
            branches:
              only: master 